apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo-task-processor
spec:
  selector:
    matchLabels:
      app: neo-task-processor
  template:
    metadata:
      labels:
        app: neo-task-processor
    spec:
      containers:
      - name: neo-task-processor
        image: tanyongang/neo-task-processor:2.0.0
        resources:
          limits:
            memory: "1024Mi"
            cpu: "500m"
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USER
          value: "guest"
        - name: RABBITMQ_PASSWORD
          value: "guest"
        - name: RABBITMQ_VHOST
          value: "/"
        
